# SPDX-License-Identifier: GPL-2.0
#
# Makefile for the sos.
#

#obj-$(CONFIG_ARM64_SOS) += sos_driver.o
#obj-$(CONFIG_ARM64_SOS) += tf_if/
#obj-$(CONFIG_ARM64_SOS) += hyp/
#obj-$(CONFIG_ARM64_SOS) += kernel/